### PR TITLE
FIX: malformed configs and slight tweaks

### PR DESCRIPTION
**Pull request by ZLLentz**
`<IoItem>` is added to an exported config if the Axis is linked deep in the IO tree. Unfortunately this makes it impossible to import the config onto any other Axis in any other IO tree. TwinCAT bug?

### CODE REVIEW

**Comment by ZLLentz** [comment]
Did we already confirm that TwinCAT can read the xml just fine once we beautify it? If so we can make `xmllint` part of the style checks/fixes for config files and tmc. We can also force all the style fixes on commit.

**Comment by klauer** [comment]
I believe I did for TMCs, but not other files...

**Comment by ZLLentz** [comment]
I will confirm that it also helps startup/nc files after fee work today

**Comment by ZLLentz** [comment]
I never investigated the XML beautification. I will make an issue for it in this repo for now.

**Pull request merged**
